const GET_CSRF_TOKEN = "GET_CSRF_TOKEN"
const LOADING = "LOADING"
const LOG_IN_USER = "LOG_IN_USER"
const SIGN_UP_USER = "SIGN_UP_USER"
const LOGOUT = "LOGOUT"
const GET_ALL_HABITS = "GET_ALL_HABITS"
const GET_MY_HABITS = "GET_MY_HABITS"
const ADD_HABIT = "ADD_HABIT"
const JOIN_HABIT = "JOIN_HABIT"
const GET_ALL_IDENTITIES = "GET_ALL_IDENTITIES"
const GET_MY_IDENTITIES = "GET_MY_IDENTITIES"
const ADD_IDENTITY = "ADD_IDENTITY"
const JOIN_IDENTITY = "JOIN_IDENTITY"
const ADD_STEP = "ADD_STEP"


export {
    GET_CSRF_TOKEN,
    LOADING,
    LOG_IN_USER,
    SIGN_UP_USER,
    LOGOUT,
    GET_ALL_HABITS,
    GET_MY_HABITS,
    ADD_HABIT,
    JOIN_HABIT,
    GET_ALL_IDENTITIES,
    GET_MY_IDENTITIES,
    ADD_IDENTITY,
    JOIN_IDENTITY,
    ADD_STEP

}